POST http://localhost:4000/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"sabrina1@mail.com2",
    "password":"password123"
}

### 
POST http://localhost:4000/login
=======
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"tata@mail.com",
    "password":"password123"
}

###
GET http://localhost:4000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRhdGEiLCJlbWFpbCI6InRhdGFAbWFpbC5jb20iLCJpYXQiOjE2ODM3MjkyMTh9.7MoJtDli9siDd_xp0xi36KCjQHiHo2aJsG_eVaxnd1w
